.dashGooglePicker_js_metadata <- function() {
deps_metadata <- list(`dash_google_picker` = structure(list(name = "dash_google_picker",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-GooglePicker.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashGooglePicker",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_google_picker` = structure(list(name = "dash_google_picker",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-GooglePicker.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashGooglePicker",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_google_picker` = structure(list(name = "dash_google_picker",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_google_picker.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashGooglePicker",
all_files = FALSE), class = "html_dependency"),
`dash_google_picker` = structure(list(name = "dash_google_picker",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_google_picker.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashGooglePicker",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
